# Generated by Django 3.2.7 on 2021-09-22 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('hostname', models.CharField(max_length=50)),
                ('pingable', models.BooleanField(default=False)),
                ('last_ping', models.DateTimeField(default=datetime.datetime(2001, 1, 1, 1, 0))),
                ('device_model', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('serial_1', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_2', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_3', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_4', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_5', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_6', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_7', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_8', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('serial_9', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('pingable', 'ip'),
            },
        ),
    ]
