# Generated by Django 3.2.7 on 2021-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='configuration',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
