# Generated by Django 3.2.7 on 2021-09-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice', '0002_networkdevice_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'ordering': ('pingable', '-last_ping')},
        ),
    ]
