# Generated by Django 3.2.7 on 2021-09-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice', '0004_alter_networkdevice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'ordering': ['pingable', '-last_ping']},
        ),
    ]
