# Generated by Django 3.2.7 on 2021-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkdevice', '0006_alter_networkdevice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='version',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
